# Generated by Django 5.0.6 on 2024-07-09 18:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
